### ISSUE TITLE
"Nothing to see here..." on API generation results screen

### ISSUE THREAD

**Issue by stigzler** [otakupahp/sdk-license-manager-for-woocommerce#2]
Hi,

This message is displayed instead of the the keys, rendering the plugin useless. Shame, as it looks really good otherwise. 

Host: A2
Wordpress: 5.7.1

Server:
Server architecture | Linux 3.10.0-962.3.2.lve1.5.49.el7.x86_64 x86_64
Web server | Apache
PHP version | 7.3.27 (Supports 64bit values)
PHP SAPI | litespeed
PHP max input variables | 10000
PHP time limit | 300
PHP memory limit | 768M
Max input time | -1
Upload max filesize | 128M
PHP post max size | 128M
cURL version | 7.71.0 OpenSSL/1.1.1d
Is SUHOSIN installed? | No
Is the Imagick library available? | Yes
Are pretty permalinks supported? | Yes
.htaccess rules | Your .htaccess file contains only core WordPress features.

MySQL:
Extension | mysqli
Server version | 10.3.27-MariaDB-cll-lve
Client version | mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $
Database username | niftymon_a2wp726
Database host | localhost
Database name | niftymon_a2wp726
Table prefix | wpsq_
Database charset | utf8mb4
Database collation | utf8mb4_unicode_ci

Hope you can help.

**Comment by stigzler** [comment]
Update. Disabled all plugins and re-enabled yours. Now get a "fatal error" on trying to generate the keys:

"Fatal error: Uncaught Error: Call to undefined function LicenseManagerForWooCommerce\Controllers\wc_api_hash() in ..."

I'll omit the rest due to file paths etc, but can recreate and forward if you need it. Do hope you can help as my dev stalled at the moment.

**Comment by otakupahp** [comment]
Hello, are you talking about the License manager plugin or the API?

**Comment by stigzler** [comment]
Hi. Sorry for the delay in response. Just to let you know it's now fixed following updating the plugin. Thanks
